DROP DATABASE IF EXISTS kinkyshop;
CREATE DATABASE kinkyshop;

SET foreign_key_checks = 0;

CREATE TABLE products (
	ID INT NOT NULL PRIMARY KEY auto_increment,
	name VARCHAR(64) NOT NULL,
	category VARCHAR(64) NOT NULL,
	thumbnail_url VARCHAR(255)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE users(
	ID INT NOT NULL PRIMARY KEY auto_increment,
	username VARCHAR(32) NOT NULL,
	password VARCHAR(32) NOT NULL,
	email VARCHAR(255) NOT NULL
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE user_data(
	ID INT NOT NULL PRIMARY KEY,
	address VARCHAR(255) NOT NULL,
	phone VARCHAR(10),
	data VARCHAR(255),
	FOREIGN KEY (ID) REFERENCES users(ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE warehouse(
	ID INT NOT NULL PRIMARY KEY,
	name VARCHAR(64) NOT NULL,
	country VARCHAR(32) NOT NULL,
	location VARCHAR(255)
	ON UPDATE CASCADE
	ON DELETE CASCADE
);

CREATE TABLE productsAvailable(
	ProductID INT NOT NULL,
	Warehouse INT NOT NULL,
	Quantity INT NOT NULL DEFAULT 0,
	PRIMARY KEY(ProductID,Warehouse).
	FOREIGN KEY(Warehouse) REFERENCES warehouse(ID)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
);

SET foreign_key_checks = 1;